Flag to see all NewReport events
tellor-io/disputable-values-monitor pull request #53
Opened 2022-10-18 17:47 UTC by tallywiesenberg

Some data types are very important, but rarely reported. This change adds a flag that alerts on all NewReport events on the given chain.

Implements click, unimplements argparse, and re-implements the `--wait` option as a `click` option

2022-10-18 19:00 UTC, oraclown requested changes
Thanks @tallywiesenberg ! Left a refactoring suggestion. Also why migration to click? It's a big import. Not against it, just curious about the reason

2022-10-19 13:40 UTC, tallywiesenberg commented on src/tellor_disputables/alerts.py
> +        if new_report.disputable is not None:
true! corrected

2022-10-19 13:41 UTC, tallywiesenberg commented
> Thanks @tallywiesenberg ! Left a refactoring suggestion. Also why migration to click? It's a big import. Not against it, just curious about the reason

Ah, I used click to be consistent with `telliot-feeds` and because I like the decorator functionality.

2022-10-19 13:52 UTC, oraclown approved these changes
Thanks @tallywiesenberg

2022-10-19 13:52 UTC, merged